export const

  SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS',
  USER_SET_TOKEN = 'USER_SET_TOKEN',
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  USER_LOGOUT = 'USER_LOGOUT',

  GET_POSTS = 'GET_POSTS',
  GET_OWN_POSTS_SUCCESS = 'GET_OWN_POSTS_SUCCESS',
  GET_FRIENDS_POSTS_SUCCESS = 'GET_FRIENDS_POSTS_SUCCESS',
  SAVE_NEW_POST_SUCCESS = 'SAVE_NEW_POST_SUCCESS',

  GET_LIST_USERS_SUCCESS = 'GET_LIST_USERS_SUCCESS',
  GET_LIST_FRIENDS_SUCCESS = 'GET_LIST_FRIENDS_SUCCESS',
  CLEAR_INPUT_FRIENDS_LIST = 'CLEAR_INPUT_FRIENDS_LIST',
  CLEAR_INPUT_USERS_LIST = 'CLEAR_INPUT_USERS_LIST',
  SUBSCRIBE_SUCCESS = 'SUBSCRIBE_SUCCESS',
  UNSUBSCRIBE_SUCCESS = 'UNSUBSCRIBE_SUCCESS',

  SHOW_ERROR = 'SHOW_ERROR',
  DISPLAY_ERROR = 'DISPLAY_ERROR'